# Generated by Django 6.0.1 on 2026-02-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_category_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
